In [1]:
import pandas
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_excel(r'C:\Users\hp\Downloads\26-07-2024.xlsx')
df

,Muncipal_Corporation,No_Of_Food_delivery_units,Quantity_delivery_from_each_Gowdown,No_of_employees,No.of_anna_canteen,Preparation_time_for_each_canteen,Food_temperature,No_of_Items,Total_cost,No.of_customers,Total_available_food_plates,No.of_plates_consumed,No.of_feedbacks_received,No.of_positive_feedbacks,No.of_negative_feedbacks,Food_weight_at_annacanteen,No.of_donations,Total_tokens_generated
0,Corporation1,Gowdown1,600kg,15,Canteen1,1hrs,135°F,7,50000,260,300,260,68.0,50,12,200kg,108,260
1,Corporation1,Gowdown1,600kg,15,Canteen2,1hrs,135°F,7,50000,280,300,280,98.0,64,12,200kg,120,280
2,Corporation1,Gowdown1,600kg,15,Canteen3,1hrs,135°F,7,50000,300,300,300,59.0,69,18,200kg,90,300
3,Corporation1,Gowdown2,750kg,25,Canteen1,2hrs,135°F,7,60000,300,300,300,62.0,59,12,265kg,109,300
4,Corporation1,Gowdown2,750kg,25,Canteen2,2hrs,135°F,7,60000,200,300,200,75.0,75,9,265kg,83,200
5,Corporation1,Gowdown2,750kg,25,Canteen3,2hrs,135°F,7,60000,150,300,150,31.0,70,17,265kg,109,150
6,Corporation1,Gowdown2,750kg,25,Canteen4,2hrs,135°F,7,60000,290,300,290,34.0,61,19,265kg,101,290
7,Corporation1,Gowdown3,600kg,16,Canteen1,1hrs,135°F,7,50000,265,300,265,65.0,66,15,200kg,120,265
8,Corporation1,Gowdown3,600kg,16,Canteen2,1hrs,135°F,7,50000,213,300,213,NaN,67,10,200kg,84,213

In [2]:
df1=pd.DataFrame(df)
df1

,Muncipal_Corporation,No_Of_Food_delivery_units,Quantity_delivery_from_each_Gowdown,No_of_employees,No.of_anna_canteen,Preparation_time_for_each_canteen,Food_temperature,No_of_Items,Total_cost,No.of_customers,Total_available_food_plates,No.of_plates_consumed,No.of_feedbacks_received,No.of_positive_feedbacks,No.of_negative_feedbacks,Food_weight_at_annacanteen,No.of_donations,Total_tokens_generated
0,Corporation1,Gowdown1,600kg,15,Canteen1,1hrs,135°F,7,50000,260,300,260,68.0,50,12,200kg,108,260
1,Corporation1,Gowdown1,600kg,15,Canteen2,1hrs,135°F,7,50000,280,300,280,98.0,64,12,200kg,120,280
2,Corporation1,Gowdown1,600kg,15,Canteen3,1hrs,135°F,7,50000,300,300,300,59.0,69,18,200kg,90,300
3,Corporation1,Gowdown2,750kg,25,Canteen1,2hrs,135°F,7,60000,300,300,300,62.0,59,12,265kg,109,300
4,Corporation1,Gowdown2,750kg,25,Canteen2,2hrs,135°F,7,60000,200,300,200,75.0,75,9,265kg,83,200
5,Corporation1,Gowdown2,750kg,25,Canteen3,2hrs,135°F,7,60000,150,300,150,31.0,70,17,265kg,109,150
6,Corporation1,Gowdown2,750kg,25,Canteen4,2hrs,135°F,7,60000,290,300,290,34.0,61,19,265kg,101,290
7,Corporation1,Gowdown3,600kg,16,Canteen1,1hrs,135°F,7,50000,265,300,265,65.0,66,15,200kg,120,265
8,Corporation1,Gowdown3,600kg,16,Canteen2,1hrs,135°F,7,50000,213,300,213,NaN,67,10,200kg,84,213

In [3]:
df.head()

,Muncipal_Corporation,No_Of_Food_delivery_units,Quantity_delivery_from_each_Gowdown,No_of_employees,No.of_anna_canteen,Preparation_time_for_each_canteen,Food_temperature,No_of_Items,Total_cost,No.of_customers,Total_available_food_plates,No.of_plates_consumed,No.of_feedbacks_received,No.of_positive_feedbacks,No.of_negative_feedbacks,Food_weight_at_annacanteen,No.of_donations,Total_tokens_generated
0,Corporation1,Gowdown1,600kg,15,Canteen1,1hrs,135°F,7,50000,260,300,260,68.0,50,12,200kg,108,260
1,Corporation1,Gowdown1,600kg,15,Canteen2,1hrs,135°F,7,50000,280,300,280,98.0,64,12,200kg,120,280
2,Corporation1,Gowdown1,600kg,15,Canteen3,1hrs,135°F,7,50000,300,300,300,59.0,69,18,200kg,90,300
3,Corporation1,Gowdown2,750kg,25,Canteen1,2hrs,135°F,7,60000,300,300,300,62.0,59,12,265kg,109,300
4,Corporation1,Gowdown2,750kg,25,Canteen2,2hrs,135°F,7,60000,200,300,200,75.0,75,9,265kg,83,200